---
- name: Check Ubuntu version
  fail:
    msg: '{{ ansible_distribution_version }} is not an acceptable version of Ubuntu for this role'
  when:
    - not ansible_distribution_version is version_compare(18.04, '=')
    - not ansible_distribution_version is version_compare(20.04, '=')

- include_tasks: setup.yml

- include_tasks: initialize.yml
- include_tasks: configure.yml

- meta: flush_handlers

- name: Ensure PostgreSQL is started and enabled on boot.
  service:
    name: "{{ postgresql_daemon }}"
    state: "started"
    enabled: "{{ postgresql_service_enabled }}"

# Configure PostgreSQL.
- import_tasks: users.yml
- import_tasks: databases.yml
- import_tasks: repslots.yml
